####################################################################################
####################################################################################
## Script Name: 4_WelfareCalculation.R##
## Purpose of the script: This script is built on the excel files generated by the DemandCurves
## scripts. It uses demand curves and the equilibrium quantity and price of water rights traded
## under simulation scenarios to calculate the welfare gains from water rights trading by
## WMAs. The outputs of this scripts are .rdata files used to generate Figure 3 in the paper
## and excel files of welfare gains by WMAs that will be used by Stata to generate the tables. 
## This script is used to estimate welfare gains under scenarios B, C and D of Figure 3, so one
## needs to comment out the directories other scenarios. 
##
##
##
## Special Requirements: excel files generated from DemandCurves files
##
## Author: Jiameng Zheng
## Email: jiamengz@illinois.edu
## 
##
##
######################################################################################
######################################################################################

rm(list=ls())
library(dplyr)
library(sf)
library(usdata)
library(ggplot2)
library(maps)
library(ggrepel)

################## set up #########################

docDir <- "C:/Users/jiamengz/OneDrive/PCHES/"
projCodeDir <- paste0(docDir, "waterRightsCumulationCurves-master/")
gdrBase <- "C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/"
projGdrDir <- paste0(gdrBase, "waterRightsCumulations/")
wwrDir <- paste0(projGdrDir, "wwrData/")
cumuDir <- paste0(projGdrDir, "output/")
stateDataDir <- paste0(projGdrDir, "inputData/")
outDir <- paste0(cumuDir, "curveFitting/")

##scenerio Dir
# This is Scenario B
scenDir <- paste0(wwrDir, "withoutStorage_RegionVol/")


## use the same codes for cutoff welfare estimations ##
# This is Scenario C
#scenDir <- paste0(wwrDir, "waterRunsOutCutoffs/")
#scenDir <- paste0(wwrDir, "waterRunsOutCutoffs_SMGA/")

SWwelAgr <- list.files(paste0(scenDir), "_SWWelfareAg",full.names=T)
SWwelUrb<- list.files(paste0(scenDir), "_SWWelfareUrb",full.names=T)

fileNames <- sapply(strsplit(SWwelAgr, "/"), "[[", length(strsplit(SWwelAgr[1],"/")[[1]]))
stAbbr <- sapply(strsplit(fileNames, "Market"), "[[", 1)
stateNames <- tolower(abbr2state(stAbbr))

# create empty dataframe
summary_df <- as.data.frame(matrix(ncol=8, nrow = 0))
colnames(summary_df) <- c("State", "Region", "SW_rowSum", "SW_colSum", "SW_allSum","GW_rowSum","GW_colSum","GW_allSum")

for (st_tmp in stAbbr) {
#st_tmp <- 'ca'
SWagr <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_SWWelfareAg.csv",sep="")), row.names=1)
SWurb <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_SWWelfareUrb.csv",sep="")), row.names=1)

SWagr <- mutate_all(SWagr, function (x) as.numeric(as.character(x)))
SWagr <- mutate_all(SWagr, function (x) pmin(x, 0))
#SWagr_sum <- sum(SWagr, na.rm=TRUE)

SWurb <- mutate_all(SWurb, function (x) as.numeric(as.character(x)))
SWurb <- mutate_all(SWurb, function (x) pmax(x, 0))
#SWurb_sum <- sum(SWurb, na.rm=TRUE)

SW_dff <- SWurb + SWagr

SW_urbsquare <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_SWUrbSquare.csv",sep="")), row.names=1)
SW_urbsquare <- mutate_all(SW_urbsquare, function (x) pmax(x,0))

SW_CS <- SWurb - SW_urbsquare
SW_PS <- SW_dff - SW_CS

SW_colSum <- colSums(SW_CS, na.rm=TRUE)
SW_rowSum <- rowSums(SW_PS, na.rm=TRUE)
SW_allSum <- SW_colSum + SW_rowSum

#SW_colSum_df = data.frame(region=names(SW_colSum), SW_colSum=SW_colSum, row.names=NULL)
#SW_rowSum_df = data.frame(region=names(SW_rowSum), SW_rowSum=SW_rowSum, row.names=NULL)
#SW_allSum_df = data.frame(region=names(SW_allSum), SW_allSum=SW_allSum, row.names=NULL)
SW_colSum_df = as.data.frame(SW_colSum)
rownames(SW_colSum_df) <- NULL
SW_colSum_df$Region = names(SW_rowSum)
SW_rowSum_df = as.data.frame(SW_rowSum)
rownames(SW_rowSum_df) <- NULL
SW_rowSum_df$Region = names(SW_rowSum)
SW_allSum_df = as.data.frame(SW_allSum)
rownames(SW_allSum_df) <- NULL
SW_allSum_df$Region = names(SW_rowSum)

tmp_SW_df = merge(merge(SW_rowSum_df,SW_colSum_df,by='Region'), SW_allSum_df, by='Region')

#SW_diff <- SWagr_sum + SWurb_sum

GWagr <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_GWWelfareAg.csv",sep="")), row.names=1)
GWurb <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_GWWelfareUrb.csv",sep="")), row.names=1)

GWagr <- mutate_all(GWagr, function (x) as.numeric(as.character(x)))
GWagr <- mutate_all(GWagr, function (x) pmin(x, 0))
#GWagr_sum <- sum(GWagr, na.rm=TRUE)

GWurb <- mutate_all(GWurb, function (x) as.numeric(as.character(x)))
GWurb <- mutate_all(GWurb, function (x) pmax(x, 0))
#GWurb_sum <- sum(GWurb, na.rm=TRUE)

GW_dff <- GWagr + GWurb
#welfare_combine <- SW_diff + GW_diff

GW_urbsquare <- read.csv(paste0(scenDir, paste(st_tmp,"MarketTrades_GWUrbSquare.csv",sep="")), row.names=1)
GW_urbsquare <- mutate_all(GW_urbsquare, function (x) pmax(x,0))

GW_CS <- GWurb - GW_urbsquare
GW_PS <- GW_dff - GW_CS

GW_colSum <- colSums(GW_CS, na.rm=TRUE)
GW_rowSum <- rowSums(GW_PS, na.rm=TRUE)
GW_allSum <- GW_colSum + GW_rowSum

GW_colSum_df = as.data.frame(GW_colSum)
rownames(GW_colSum_df) <- NULL
GW_colSum_df$Region = names(SW_rowSum)
GW_rowSum_df = as.data.frame(GW_rowSum)
rownames(GW_rowSum_df) <- NULL
GW_rowSum_df$Region = names(SW_rowSum)
GW_allSum_df = as.data.frame(GW_allSum)
rownames(GW_allSum_df) <- NULL
GW_allSum_df$Region = names(SW_rowSum)

tmp_GW_df = merge(merge(GW_rowSum_df,GW_colSum_df,by='Region'), GW_allSum_df, by='Region')

tmp_df = merge(tmp_SW_df, tmp_GW_df, by='Region') # combine GW and SW temporary dataframe
tmp_df$State = st_tmp # add state column

tmp_df <- tmp_df[, c(8,1,2,3,4,5,6,7)] # reorder the column

# append to the dataframe
#summary_df[nrow(summary_df)+1, ]=c(st_tmp, SWagr_sum, SWurb_sum, SW_diff, GWagr_sum, GWurb_sum, GW_diff, welfare_combine)
summary_df <- rbind(summary_df, tmp_df)
}
summary_df$welfare_combined <- summary_df$SW_allSum+summary_df$GW_allSum
summary_df$state_name <- toupper(summary_df$State)
summary_df$state_name<- state.name[match(summary_df$state_name, state.abb)]
summary_df$welfare <- summary_df$welfare_combined * 60 * 60 * 6 * 100

summary_df$welfare[summary_df$welfare == 0] <- NA
summary_df$ps <-summary_df$SW_rowSum + summary_df$GW_rowSum
summary_df$ps <- summary_df$ps * 60 * 60 * 6 * 100
summary_df$ps[summary_df$ps == 0] <- NA
summary_df$ps[summary_df$ps < 0] <- NA
summary_df$psinmill <- summary_df$ps/1000000
summary_df$cs <-summary_df$SW_colSum+ summary_df$GW_colSum
summary_df$cs <- summary_df$cs * 60 * 60 * 6 * 100
summary_df$cs[summary_df$cs == 0] <- NA
summary_df$cs[summary_df$cs < 0] <- NA
summary_df$csinmill <- summary_df$cs/1000000
boundary <- st_read("C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/backgroundGISData/WWRtradeBounds.shp")
#boundary <- st_read("~/OneDrive/PCHES/data/welfare_calculation/Data/backgroundGISData/WWRtradeBounds.shp")
boundary <- st_transform(boundary, crs = 4269)
df_spjoin <- merge(boundary, summary_df, by.x="basinName", by.y="Region", all.x=TRUE)
df_spjoin$welfare <- as.numeric(df_spjoin$welfare)
df_spjoin$logwel <- log(df_spjoin$welfare)
df_spjoin$welinmill <- df_spjoin$welfare/1000000


city <- st_read("C:/Users/jiamengz/OneDrive/PCHES/data/GIS files/ne_10m_populated_places.shp")
bigCities <- c( "San Francisco", "Los Angeles", "San Diego", "Portland", "Seattle", "Spokane", "Boise", "Idaho Falls", "Denver", "Colorado Springs", "Phoenix", "Tucson", "Las Vegas", "Reno", "Salt Lake City", "Provo","Albuquerque", "Las Cruces", "Missoula", "Billings", "Cheyenne", "Casper")
bigcity <- subset(city, NAME %in% bigCities & SOV0NAME == "United States" & ADM1NAME != "Maine"  )
bigcity <- bigcity[!(bigcity$NAME == "Las Vegas" & bigcity$ADM1NAME == "New Mexico" ),]
bigcity <- st_as_sf(bigcity, coords = c("LONGITUDE", "LATITUDE"), crs = 4269)
bigcity <- st_transform(bigcity, crs = 4269)

# comment out unused file names #
save(df_spjoin, bigcity, file = "C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/welfare_data_simulated.rdata")

#writexl::write_xlsx(summary_df, "C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/welfare_summary_simulated.xlsx" )
#writexl::write_xlsx(summary_df, "C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/welfare_summary_cutoffs.xlsx" )
writexl::write_xlsx(summary_df, "C:/Users/jiamengz/OneDrive/PCHES/data/welfare_calculation/Data/welfare_summary_cutoffs_SGMA.xlsx" )
